Resources:
  UploadFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: uploadFile.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        Upload:
          Type: Api
          Properties:
            Path: /link
            Method: post
            # Auth:
            #   Authorizer: NONE

  ExtractEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: extractEmail.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        Extract:
          Type: Api
          Properties:
            Path: /parser
            Method: post
            # Auth:
            #   Authorizer: NONE